@startuml
class java.awt.Image
class java.awt.event.KeyEvent
class java.awt.event.KeyListener
class java.io.IOException
class java.nio.file.Files
class java.nio.file.Path
class java.util.ArrayList
class java.util.Random
class javax.sound.sampled.Clip
class javax.swing.ImageIcon
class javax.swing.JPanel
class org.json.simple.JSONObject
class pendu.Controleur.DataControleur
class pendu.Controleur.ViewControleur
class pendu.Game.Pendu
class pendu.Listener.ListenerChar
class pendu.Listener.ListenerOption
class pendu.Menu.MenuChoixGame
class pendu.Menu.MenuChooseList
class pendu.Menu.MenuList
class pendu.Menu.MenuOption
class pendu.Object.Option
class pendu.librairy.Langue
class pendu.librairy.Police
class pendu.librairy.ReadJson
class pendu.librairy.Sound
class pendu.librairy.WriteJSon
class pendu.panel.panelClavier
class pendu.panel.panelLabel
pendu.Controleur.DataControleur ..> java.awt.Image
pendu.Controleur.DataControleur ..> java.io.IOException
pendu.Controleur.DataControleur ..> java.nio.file.Files
pendu.Controleur.DataControleur ..> java.nio.file.Path
pendu.Controleur.DataControleur ..> java.util.ArrayList
pendu.Controleur.DataControleur ..> java.util.Random
pendu.Controleur.DataControleur ..> javax.sound.sampled.Clip
pendu.Controleur.DataControleur ..> javax.swing.ImageIcon
pendu.Controleur.DataControleur ..> org.json.simple.JSONObject
pendu.Controleur.DataControleur ..> pendu.Object.Option
pendu.Controleur.DataControleur ..> pendu.librairy.Langue
pendu.Controleur.DataControleur ..> pendu.librairy.Police
pendu.Controleur.DataControleur ..> pendu.librairy.ReadJson
pendu.Controleur.DataControleur ..> pendu.librairy.Sound
pendu.Controleur.DataControleur ..> pendu.librairy.WriteJSon
pendu.Controleur.ViewControleur ..> java.awt.event.KeyEvent
pendu.Controleur.ViewControleur ..> java.awt.event.KeyListener
pendu.Controleur.ViewControleur ..> java.util.ArrayList
pendu.Controleur.ViewControleur ..> javax.swing.JPanel
pendu.Controleur.ViewControleur ..> pendu.Game.Pendu
pendu.Controleur.ViewControleur ..> pendu.Listener.ListenerChar
pendu.Controleur.ViewControleur ..> pendu.Listener.ListenerOption
pendu.Controleur.ViewControleur ..> pendu.Menu.MenuChoixGame
pendu.Controleur.ViewControleur ..> pendu.Menu.MenuChooseList
pendu.Controleur.ViewControleur ..> pendu.Menu.MenuList
pendu.Controleur.ViewControleur ..> pendu.Menu.MenuOption
pendu.Controleur.ViewControleur ..> pendu.panel.panelClavier
pendu.Controleur.ViewControleur ..> pendu.panel.panelLabel
@enduml