/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import Jeux.Controleur.GuiControleur;
import Pendu.Pendu;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Utilisateur
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonPendu = new javax.swing.JButton();
        jButtonOXO = new javax.swing.JButton();
        jButtonBlackJack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jButtonPendu.setText("Pendu");
        jButtonPendu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPenduActionPerformed(evt);
            }
        });

        jButtonOXO.setText("OXO");
        jButtonOXO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOXOActionPerformed(evt);
            }
        });

        jButtonBlackJack.setText("BlackJack");
        jButtonBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBlackJackActionPerformed(evt);
            }
        });

        jButton1.setText("Dames");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButtonBlackJack)
                    .addComponent(jButtonOXO)
                    .addComponent(jButtonPendu))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButtonBlackJack, jButtonOXO, jButtonPendu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButtonPendu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOXO)
                .addGap(18, 18, 18)
                .addComponent(jButtonBlackJack)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButtonBlackJack, jButtonOXO, jButtonPendu});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPenduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPenduActionPerformed
        JTextField Text = new JTextField();
        String Mot = null;
        boolean flag =true; 
        do {
            Mot = JOptionPane.showInputDialog(null, null, "Choisissez un mot", JOptionPane.OK_OPTION);
            if(!Mot.equalsIgnoreCase("")){
                flag=false;
            }
        } while (flag);
        GuiControleur.getInstance().CallPendu(Mot);

    }//GEN-LAST:event_jButtonPenduActionPerformed

    private void jButtonOXOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOXOActionPerformed
        JRadioButton XButton = new JRadioButton("X");
        JRadioButton OButton = new JRadioButton("O");
        ButtonGroup group = new ButtonGroup();
        group.add(OButton);
        group.add(XButton);
        JPanel panel = new JPanel();
        panel.add(OButton);
        panel.add(XButton);
        int i = JOptionPane.showConfirmDialog(null, panel, "Qui commence ?", JOptionPane.YES_OPTION);
        if (i == 0) {
            if (XButton.isSelected()) {
                GuiControleur.getInstance().CallOXO("X");
            } else {
                GuiControleur.getInstance().CallOXO("O");
            }
        }
    }//GEN-LAST:event_jButtonOXOActionPerformed

    private void jButtonBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBlackJackActionPerformed
        GuiControleur.getInstance().CallBlackJack();
    }//GEN-LAST:event_jButtonBlackJackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       GuiControleur.getInstance().CallDames();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBlackJack;
    private javax.swing.JButton jButtonOXO;
    private javax.swing.JButton jButtonPendu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
